### ISSUE TITLE
Documentation of workflow for data ingestion and debugging needs to be updated.

### ISSUE THREAD

**Issue by johtoblan** [metno/use-cases-for-S-ENDA#305]
- [x] Simple case where dataproducer wants to verify if the data they have pushed into the system via the event queue is coming through by using data-test.met.no
- [x] Team-specific case where any data is not going through the event queue properly, how to debug.
- [x] Are we following [tjeneste-krav](https://it.pages.met.no/arkitektur/arkitektur-web/tjenester.html) from the architecture group.

Some of this (team-specific) should be documented in the tjeneste-repo on gitlab, and the dataproducer case should be documented in the DMH.
